sudo: required
language: generic

env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_CORE_CHECK_GCE_METADATA=False

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth active-service-account --key-file service-account.json
  - gcloud config set project main-reducer-313812
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials pkdtech-trial-multicluster-2
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker built -t dpraskumar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker-run dpraskumar/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master